version : 3

tasks:
  build:
    cmds:
      - go build -o bin/app cmd/main.go
  run:
    cmds:
      - task build 
      - ./bin/app 
  deps:
    cmds:
      - go mod download
  proto:
    cmds:
      - protoc --go_out=. --go-grpc_out=. pkg/proto/review.proto  